[project]
name = "yosegi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.3",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "ty>=0.0.1a35",
]
